version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecr: circleci/aws-ecr@9.1.0

executors:
  base:
    docker:
      - image: cimg/base:current

jobs:
  job_a:
    executor: base
    steps:
      - checkout
      - run: echo hello 1
  job_b:
    executor: base
    steps:
      - checkout
      - run: echo hello 2

workflows:
  job-workflow:
    jobs:
      - job_a
      - job_b